site:
  title: Cognito Dart Auth SDK Docs
  start_page: cognito-dart-auth-sdk::index.adoc
  url: https://cognito-dart-auth-sdk-docs.web.app/

content:
  sources:
    - url: ..
      branches: HEAD
      start_path: cognito-dart-auth-sdk/docs/components/cognito-dart-auth-sdk

ui:
  bundle:
    url: ./ui/antora-ui-custom/ui-bundle
    snapshot: true
